name = "anju-web"
main = ".open-next/worker.js"
compatibility_date = "2025-11-17"

compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[build]
command = "npm run cf-build"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.development]
name = "anju-web-development"
routes = [
  { pattern = "development-app.vocesqueabrazan.com", custom_domain = true }
]
[env.development.assets]
directory = ".open-next/assets"
binding = "ASSETS"
[env.development.observability]
enabled = true
[env.development.observability.logs]
enabled = true
invocation_logs = true
[env.development.observability.traces]
enabled = false
[env.development.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://development-api.vocesqueabrazan.com"
NEXT_PUBLIC_MCP_URL = "https://development-mcp.vocesqueabrazan.com"
NEXT_PUBLIC_WEB_URL = "https://development-app.vocesqueabrazan.com"
NEXT_PUBLIC_DOMAIN = "vocesqueabrazan.com"

[env.production]
name = "anju-web-production"
routes = [
  { pattern = "app.anju.ai", custom_domain = true }
]
[env.production.assets]
directory = ".open-next/assets"
binding = "ASSETS"
[env.production.observability]
enabled = true
[env.production.observability.logs]
enabled = true
invocation_logs = true
[env.production.observability.traces]
enabled = false
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://api.anju.ai"
NEXT_PUBLIC_MCP_URL = "https://mcp.anju.ai"
NEXT_PUBLIC_WEB_URL = "https://app.anju.ai"
NEXT_PUBLIC_DOMAIN = "anju.ai"
