const USER_STATUS_ACTIVE = 'ACTIVE';
const USER_STATUS_BLOCKED = 'BLOCKED';
const USER_STATUS = [USER_STATUS_ACTIVE, USER_STATUS_BLOCKED];

const USER_ROLE_ADMIN = 'ADMIN';
const USER_ROLES = [USER_ROLE_ADMIN];

const STATUS_COMPLETED = 'COMPLETED';
const STATUS_PENDING = 'PENDING';
const STATUS_FAILED = 'FAILED';
const STATUS_ACTIVE = 'ACTIVE';
const STATUS = [STATUS_COMPLETED, STATUS_PENDING, STATUS_FAILED, STATUS_ACTIVE];

const TYPE_MESSAGE_USER = 'USER';
const TYPE_MESSAGE_AI = 'AI';
const TYPE_MESSAGES = [TYPE_MESSAGE_USER, TYPE_MESSAGE_AI];

const LANGUAGE_EN = 'en';
const LANGUAGE_ES = 'es';
const LANGUAGES = [LANGUAGE_EN, LANGUAGE_ES];

export const constants = {
  USER_STATUS_ACTIVE,
  USER_STATUS_BLOCKED,
  USER_STATUS,
  USER_ROLE_ADMIN,
  USER_ROLES,
  STATUS_COMPLETED,
  STATUS_PENDING,
  STATUS_FAILED,
  STATUS_ACTIVE,
  STATUS,
  TYPE_MESSAGE_USER,
  TYPE_MESSAGE_AI,
  TYPE_MESSAGES,
  LANGUAGE_EN,
  LANGUAGE_ES,
  LANGUAGES,
};
