const USER_STATUS_ACTIVE = 'ACTIVE';
const USER_STATUS_BLOCKED = 'BLOCKED';
const USER_STATUS = [USER_STATUS_ACTIVE, USER_STATUS_BLOCKED];

const USER_ROLE_ADMIN = 'ADMIN';
const USER_ROLES = [USER_ROLE_ADMIN];

const STATUS_COMPLETED = 'COMPLETED';
const STATUS_PENDING = 'PENDING';
const STATUS_FAILED = 'FAILED';
const STATUS_ACTIVE = 'ACTIVE';
const STATUS = [STATUS_COMPLETED, STATUS_PENDING, STATUS_FAILED, STATUS_ACTIVE];

const SCHEMA_DEFINITION_TYPES = [
  'string',
  'number',
  'boolean',
  'object',
  'array'
];

const ROLE_MESSAGE_USER = 'user';
const ROLE_MESSAGE_ASSISTANT = 'assistant';
const ROLE_MESSAGES = [ROLE_MESSAGE_USER, ROLE_MESSAGE_ASSISTANT];

const RESOURCE_TYPE_STATIC = 'static';
const RESOURCE_TYPE_TEMPLATE = 'template';
const RESOURCE_TYPES = [RESOURCE_TYPE_STATIC, RESOURCE_TYPE_TEMPLATE];

const RESOURCE_ICON_THEME_DARK = 'dark';
const RESOURCE_ICON_THEME_LIGHT = 'light';
const RESOURCE_ICON_THEMES = [
  RESOURCE_ICON_THEME_DARK,
  RESOURCE_ICON_THEME_LIGHT
];

const LANGUAGE_EN = 'en';
const LANGUAGE_ES = 'es';
const LANGUAGES = [LANGUAGE_EN, LANGUAGE_ES];

const MIMETYPE_TEXT = 'text/plain';
const MIMETYPE_TEXT_CSV = 'text/csv';
const MIMETYPE_TEXT_HTML = 'text/html';
const MIMETYPE_VIDEO_MP4 = 'video/mp4';
const MIMETYPE_IMAGE_PNG = 'image/png';
const MIMETYPE_IMAGE_GIF = 'image/gif';
const MIMETYPE_AUDIO_MP3 = 'audio/mpeg';
const MIMETYPE_IMAGE_JPEG = 'image/jpeg';
const MIMETYPE_IMAGE_WEBP = 'image/webp';
const MIMETYPE_APPLICATION_PDF = 'application/pdf';
const MIMETYPE_APPLICATION_ZIP = 'application/zip';
const MIMETYPE_APPLICATION_RAR = 'application/x-rar-compressed';
const MIMETYPE_APPLICATION_JSON = 'application/json';
const MIMETYPE_APPLICATION_MSWORD = 'application/msword';
const MIMETYPE_APPLICATION_ZIP_WINDOWS = 'application/x-zip-compressed';
const MIMETYPE_APPLICATION_VND_MS_EXCEL = 'application/vnd.ms-excel';
const MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET =
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT =
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION =
  'application/vnd.openxmlformats-officedocument.presentationml.presentation';
const MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT =
  'application/vnd.google-apps.document';
const MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET =
  'application/vnd.google-apps.spreadsheet';
const MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION =
  'application/vnd.google-apps.presentation';
const MIMETYPE_APPLICATION_XML = 'application/xml';
const MIMETYPE_APPLICATION_JAVASCRIPT = 'application/javascript';
const MIMETYPE_APPLICATION_TYPESCRIPT = 'application/typescript';
const MIMETYPE_APPLICATION_YAML = 'application/yaml';
const MIMETYPE_APPLICATION_X_YAML = 'application/x-yaml';
const MIMETYPE_APPLICATION_TOML = 'application/toml';
const MIMETYPE_APPLICATION_X_SH = 'application/x-sh';
const MIMETYPE_APPLICATION_SQL = 'application/sql';
const MIMETYPE_APPLICATION_GRAPHQL = 'application/graphql';
const MIMETYPE_APPLICATION_LD_JSON = 'application/ld+json';
const MIMETYPE_APPLICATION_XHTML_XML = 'application/xhtml+xml';
const MIMETYPE_APPLICATION_X_HTTPD_PHP = 'application/x-httpd-php';
const MIMETYPE_APPLICATION_X_PYTHON_CODE = 'application/x-python-code';
const MIMETYPE_APPLICATION_X_WWW_FORM_URLENCODED =
  'application/x-www-form-urlencoded';
const MIMETYPE_APPLICATION_CSV = 'application/csv';
const MIMETYPE_APPLICATION_X_RUBY = 'application/x-ruby';
const MIMETYPE_APPLICATION_X_PERL = 'application/x-perl';
const MIMETYPES = [
  MIMETYPE_TEXT,
  MIMETYPE_TEXT_CSV,
  MIMETYPE_TEXT_HTML,
  MIMETYPE_VIDEO_MP4,
  MIMETYPE_IMAGE_PNG,
  MIMETYPE_IMAGE_GIF,
  MIMETYPE_AUDIO_MP3,
  MIMETYPE_IMAGE_JPEG,
  MIMETYPE_IMAGE_WEBP,
  MIMETYPE_APPLICATION_PDF,
  MIMETYPE_APPLICATION_ZIP,
  MIMETYPE_APPLICATION_RAR,
  MIMETYPE_APPLICATION_JSON,
  MIMETYPE_APPLICATION_MSWORD,
  MIMETYPE_APPLICATION_ZIP_WINDOWS,
  MIMETYPE_APPLICATION_VND_MS_EXCEL,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION,
  MIMETYPE_APPLICATION_XML,
  MIMETYPE_APPLICATION_JAVASCRIPT,
  MIMETYPE_APPLICATION_TYPESCRIPT,
  MIMETYPE_APPLICATION_YAML,
  MIMETYPE_APPLICATION_X_YAML,
  MIMETYPE_APPLICATION_TOML,
  MIMETYPE_APPLICATION_X_SH,
  MIMETYPE_APPLICATION_SQL,
  MIMETYPE_APPLICATION_GRAPHQL,
  MIMETYPE_APPLICATION_LD_JSON,
  MIMETYPE_APPLICATION_XHTML_XML,
  MIMETYPE_APPLICATION_X_HTTPD_PHP,
  MIMETYPE_APPLICATION_X_PYTHON_CODE,
  MIMETYPE_APPLICATION_X_WWW_FORM_URLENCODED,
  MIMETYPE_APPLICATION_CSV,
  MIMETYPE_APPLICATION_X_RUBY,
  MIMETYPE_APPLICATION_X_PERL
];
const TEXT_MIME_TYPES = [
  MIMETYPE_TEXT,
  MIMETYPE_TEXT_CSV,
  MIMETYPE_TEXT_HTML,
  MIMETYPE_APPLICATION_JSON,
  MIMETYPE_APPLICATION_XML,
  MIMETYPE_APPLICATION_JAVASCRIPT,
  MIMETYPE_APPLICATION_TYPESCRIPT,
  MIMETYPE_APPLICATION_YAML,
  MIMETYPE_APPLICATION_X_YAML,
  MIMETYPE_APPLICATION_TOML,
  MIMETYPE_APPLICATION_X_SH,
  MIMETYPE_APPLICATION_SQL,
  MIMETYPE_APPLICATION_GRAPHQL,
  MIMETYPE_APPLICATION_LD_JSON,
  MIMETYPE_APPLICATION_XHTML_XML,
  MIMETYPE_APPLICATION_X_HTTPD_PHP,
  MIMETYPE_APPLICATION_X_PYTHON_CODE,
  MIMETYPE_APPLICATION_X_WWW_FORM_URLENCODED,
  MIMETYPE_APPLICATION_CSV,
  MIMETYPE_APPLICATION_X_RUBY,
  MIMETYPE_APPLICATION_X_PERL
];

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

export const constants = {
  USER_STATUS_ACTIVE,
  USER_STATUS_BLOCKED,
  USER_STATUS,
  USER_ROLE_ADMIN,
  USER_ROLES,
  STATUS_COMPLETED,
  STATUS_PENDING,
  STATUS_FAILED,
  STATUS_ACTIVE,
  STATUS,
  SCHEMA_DEFINITION_TYPES,
  ROLE_MESSAGE_USER,
  ROLE_MESSAGE_ASSISTANT,
  ROLE_MESSAGES,
  LANGUAGE_EN,
  LANGUAGE_ES,
  LANGUAGES,
  MIMETYPE_TEXT,
  MIMETYPE_TEXT_CSV,
  MIMETYPE_TEXT_HTML,
  MIMETYPE_VIDEO_MP4,
  MIMETYPE_IMAGE_PNG,
  MIMETYPE_IMAGE_GIF,
  MIMETYPE_AUDIO_MP3,
  MIMETYPE_IMAGE_JPEG,
  MIMETYPE_IMAGE_WEBP,
  MIMETYPE_APPLICATION_PDF,
  MIMETYPE_APPLICATION_ZIP,
  MIMETYPE_APPLICATION_RAR,
  MIMETYPE_APPLICATION_JSON,
  MIMETYPE_APPLICATION_MSWORD,
  MIMETYPE_APPLICATION_ZIP_WINDOWS,
  MIMETYPE_APPLICATION_VND_MS_EXCEL,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION,
  MIMETYPE_APPLICATION_XML,
  MIMETYPE_APPLICATION_JAVASCRIPT,
  MIMETYPE_APPLICATION_TYPESCRIPT,
  MIMETYPE_APPLICATION_YAML,
  MIMETYPE_APPLICATION_X_YAML,
  MIMETYPE_APPLICATION_TOML,
  MIMETYPE_APPLICATION_X_SH,
  MIMETYPE_APPLICATION_SQL,
  MIMETYPE_APPLICATION_GRAPHQL,
  MIMETYPE_APPLICATION_LD_JSON,
  MIMETYPE_APPLICATION_XHTML_XML,
  MIMETYPE_APPLICATION_X_HTTPD_PHP,
  MIMETYPE_APPLICATION_X_PYTHON_CODE,
  MIMETYPE_APPLICATION_X_WWW_FORM_URLENCODED,
  MIMETYPE_APPLICATION_CSV,
  MIMETYPE_APPLICATION_X_RUBY,
  MIMETYPE_APPLICATION_X_PERL,
  MIMETYPES,
  TEXT_MIME_TYPES,
  RESOURCE_TYPE_STATIC,
  RESOURCE_TYPE_TEMPLATE,
  RESOURCE_TYPES,
  RESOURCE_ICON_THEME_DARK,
  RESOURCE_ICON_THEME_LIGHT,
  RESOURCE_ICON_THEMES,
  MAX_FILE_SIZE
};
